namespace VpSharp.Internal.NativeAttributes;

internal enum FloatAttribute
{
    AvatarX,
    AvatarY,
    AvatarZ,
    AvatarYaw,
    AvatarPitch,
    MyX,
    MyY,
    MyZ,
    MyYaw,
    MyPitch,
    ObjectX,
    ObjectY,
    ObjectZ,
    ObjectRotationX,
    ObjectRotationY,
    ObjectRotationZ,
    ObjectYaw = ObjectRotationX,
    ObjectPitch = ObjectRotationY,
    ObjectRoll = ObjectRotationZ,
    ObjectRotationAngle,
    TeleportX,
    TeleportY,
    TeleportZ,
    TeleportYaw,
    TeleportPitch,
    ClickHitX,
    ClickHitY,
    ClickHitZ,
    JoinX,
    JoinY,
    JoinZ,
    JoinYaw,
    JoinPitch,
    InviteX,
    InviteY,
    InviteZ,
    InviteYaw,
    InvitePitch
}
