//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VpSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VpSharp.res.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target avatar is not in the world..
        /// </summary>
        internal static string AvatarNotInWorld {
            get {
                return ResourceManager.GetString("AvatarNotInWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot invite non-existent user..
        /// </summary>
        internal static string CannotInviteNonExistentUser {
            get {
                return ResourceManager.GetString("CannotInviteNonExistentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot join non-existent user..
        /// </summary>
        internal static string CannotJoinNonExistentUser {
            get {
                return ResourceManager.GetString("CannotJoinNonExistentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot login due to incomplete configuration..
        /// </summary>
        internal static string CannotLogin_IncompleteConfiguration {
            get {
                return ResourceManager.GetString("CannotLogin_IncompleteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username and password constitute an invalid login..
        /// </summary>
        internal static string CannotLogin_InvalidLogin {
            get {
                return ResourceManager.GetString("CannotLogin_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value in the configuration is too long. (BotName?).
        /// </summary>
        internal static string CannotLogin_StringTooLong {
            get {
                return ResourceManager.GetString("CannotLogin_StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login request timed out..
        /// </summary>
        internal static string CannotLogin_Timeout {
            get {
                return ResourceManager.GetString("CannotLogin_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation cannot be performed on the client&apos;s current avatar..
        /// </summary>
        internal static string CannotUseSelf {
            get {
                return ResourceManager.GetString("CannotUseSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the server timed out..
        /// </summary>
        internal static string ConnectionTimedOut {
            get {
                return ResourceManager.GetString("ConnectionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection to a universe server is required for this operation..
        /// </summary>
        internal static string ConnectionToUniverseServerRequired {
            get {
                return ResourceManager.GetString("ConnectionToUniverseServerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection to a world server is required for this operation..
        /// </summary>
        internal static string ConnectionToWorldServerRequired {
            get {
                return ResourceManager.GetString("ConnectionToWorldServerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extension with the type {0} is added to this client..
        /// </summary>
        internal static string NoSuchExtension {
            get {
                return ResourceManager.GetString("NoSuchExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to modify world settings..
        /// </summary>
        internal static string NotAllowedToModifyWorldSettings {
            get {
                return ResourceManager.GetString("NotAllowedToModifyWorldSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to perform an operation that requires a connection to a world server..
        /// </summary>
        internal static string NotInWorld {
            get {
                return ResourceManager.GetString("NotInWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to perform an operation on a nonexistent object..
        /// </summary>
        internal static string ObjectNotFound {
            get {
                return ResourceManager.GetString("ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius must be greater than or equal to 1..
        /// </summary>
        internal static string RadiusMustBeGreaterThan1 {
            get {
                return ResourceManager.GetString("RadiusMustBeGreaterThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specified value is too long..
        /// </summary>
        internal static string StringTooLong {
            get {
                return ResourceManager.GetString("StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type cannot be abstract..
        /// </summary>
        internal static string TypeCannotBeAbstract {
            get {
                return ResourceManager.GetString("TypeCannotBeAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must inherit from {0}..
        /// </summary>
        internal static string TypeMustInherit {
            get {
                return ResourceManager.GetString("TypeMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified remote endpoint is not supported..
        /// </summary>
        internal static string UnsupportedEndpoint {
            get {
                return ResourceManager.GetString("UnsupportedEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported object type..
        /// </summary>
        internal static string UnsupportedObjectType {
            get {
                return ResourceManager.GetString("UnsupportedObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        internal static string ValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the universe server was lost, or connecting to the world failed..
        /// </summary>
        internal static string WorldLoginError {
            get {
                return ResourceManager.GetString("WorldLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World name cannot be null or empty..
        /// </summary>
        internal static string WorldNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("WorldNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be 0.0 through 1.0..
        /// </summary>
        internal static string ZeroThroughOne {
            get {
                return ResourceManager.GetString("ZeroThroughOne", resourceCulture);
            }
        }
    }
}
